### ISSUE TITLE
There was a problem playing this item

### ISSUE THREAD

**Issue by 910nico** [manfer/AIPTV.bundle#1]
With Plex v0.9.12.9, i tried to play samples from sample.xspf, then each time i click on a channel this error message appear 'There was a problem playing this item'.
I tested with chrome and firefox.

**Comment by manfer** [comment]
Looks like Russia Today streams (RT News and RT Documentary) and DY365 are not working any more. But the rest of the sample channels should work fine.

Tested with Plex Media Server 0.9.12.8.1362-4601e39.

I'm going to look if there is an update and try to see if something changed in Plex.

Thanks for the report.

**Comment by manfer** [comment]
For the streams to work in Plex Web (chrome, firefox) you have to be sure to uncheck an option on Plex Web Settings.

You have to click the settings button on the top right. And into the `Plex Web` Settings on section `Player` (in advance mode) `Direct Play` must be unchecked.

**Comment by 910nico** [comment]
Thanks manfer, i unchecked this button and now channels work fine :)  Awesome !
